project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Weekly Diary"
  author: "Lingqiao Yang"
  date: "2025/2/4"
  chapters:
    - index.qmd
    - wk1.qmd
    - wk2.qmd
    - wk3.qmd
    - wk6.qmd
    - wk7.qmd
    - references.qmd

bibliography: references.bib
nocite: "@*"


format:
  html:
    theme: cosmo
  

editor: visual

